### ISSUE TITLE
 Error adding app on product page

### ISSUE THREAD

**Issue by lucioedfonseca** [vtex-apps/store#197]
**Describe the bug**
I need to add an app on the product page I can not even add in the interface as allowed and no blocks.
The app does not appear and on the front gives an "undefined interface" error and does not appear on the console when we are __RENDER_8_COMPONENTS__

**To Reproduce**

just add an app that has ready in store

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/3405711/54754082-6e21f000-4bc1-11e9-9070-708cd9fca37b.png)

**Desktop (please complete the following information):**
 - windons 10
 - Browser [chrome]

**Additional context**
We were able to add until Monday morning

**Comment by victorhmp** [comment]
Closing this since it has been stale for too long.
