### ISSUE TITLE
Brand shelf/gallary in homepage

### ISSUE THREAD

**Issue by Jayendra88** [vtex-apps/store#199]
**Is your feature request related to a problem? Please describe.**
list of brands should be displayed on homepage so user can easily access the brands

**Describe the solution you'd like**
Show list of brands (sorted list) as a gallery/shelf on homepage
Admin can show selected brands in home page
Allow query images for brands
Add load more button and when it is clicked redirect to a new page which contains all the brands.

**Describe alternatives you've considered**
Allow new block into `store.home` so we can create a new application

**Comment by victorhmp** [comment]
Closing this since `allowed` lists are not considered anymore for `store` interfaces.
